services:
  api:
    build:
      context: .
    container_name: hexagonal-architecture-api
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - hexagonal_architecture
  postgres:
    container_name: hexagonal-architecture-postgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - hexagonal_architecture
    volumes:
      - postgres:/var/lib/postgresql
networks:
  hexagonal_architecture:
volumes:
  postgres:
